is:
  - headers.acceptJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.clientOrAgentNotAuthorised
displayName: Sample endoint [test only]
description: This endpoint allows a user to see an example endpoint.
(annotations.sandboxData): !include scenarios/sample.md
(annotations.scope): "read:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
body:
  application/json:
    type: !include schemas/sample/post_request.json
    examples:
     example-1:
      description: sample request body
      value: !include examples/sample/post_request.json
responses:
  201:
    body:
      application/json:
        type: !include schemas/sample/post_response.json
        examples:
          example-1:
            description: Sample example 1
            value: !include examples/sample/post_response.json
    headers:
      X-CorrelationId:
        example: c75f40a6-a3df-4429-a697-471eeec46435
        description: Unique ID for operation tracking <br> String, 36 characters.